/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.moeketsi.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Moeketsi Tsotetsi
 */
public class Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnAddClass = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnAddNewStudents = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnAddNewSubject = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnPrintStudentsReports = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnExit = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Class");

        mnAddClass.setText("Add Class");
        mnAddClass.addActionListener(this::mnAddClassActionPerformed);
        jMenu1.add(mnAddClass);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Students");

        mnAddNewStudents.setText("Add New Student");
        mnAddNewStudents.addActionListener(this::mnAddNewStudentsActionPerformed);
        jMenu2.add(mnAddNewStudents);

        jMenuItem2.setText("Add Student Marks ");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Subjects");

        mnAddNewSubject.setText("Add New Subject");
        mnAddNewSubject.addActionListener(this::mnAddNewSubjectActionPerformed);
        jMenu3.add(mnAddNewSubject);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Reports");

        mnPrintStudentsReports.setText("Print Student Reports");
        mnPrintStudentsReports.addActionListener(this::mnPrintStudentsReportsActionPerformed);
        jMenu4.add(mnPrintStudentsReports);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Exit");

        mnExit.setText("Close Application");
        mnExit.addActionListener(this::mnExitActionPerformed);
        jMenu5.add(mnExit);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 854, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnAddNewStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAddNewStudentsActionPerformed
        AddStudent ar = new AddStudent();
        ar.setVisible(true);
        
    }//GEN-LAST:event_mnAddNewStudentsActionPerformed

    private void mnAddClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAddClassActionPerformed
        Home homeFrame = new Home();
        homeFrame.setVisible(true);
        
    }//GEN-LAST:event_mnAddClassActionPerformed

    private void mnAddNewSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAddNewSubjectActionPerformed
        Subjects subjectsFrame = new Subjects();
        subjectsFrame.setVisible(true);
    }//GEN-LAST:event_mnAddNewSubjectActionPerformed

    private void mnPrintStudentsReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPrintStudentsReportsActionPerformed
        ReportFrame reportFrame = new ReportFrame();
        reportFrame.setVisible(true);
    }//GEN-LAST:event_mnPrintStudentsReportsActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        int res = JOptionPane.showConfirmDialog(null, "Do you want to exit?", 
               "Close", JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
        if(res == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_mnExitActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        MarksFrame mf = new MarksFrame();
        mf.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mnAddClass;
    private javax.swing.JMenuItem mnAddNewStudents;
    private javax.swing.JMenuItem mnAddNewSubject;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenuItem mnPrintStudentsReports;
    // End of variables declaration//GEN-END:variables
}
