/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.moeketsi.gui;

import com.moeketsi.classes.Student;
import com.moeketsi.classes.Subject;
import com.moeketsi.classes.SubjectResult;
import com.moeketsi.classes.SubjectStreams;
import com.moeketsi.dao.StudentDAO;
import com.moeketsi.dao.SubjectDAO;
import com.moeketsi.dao.SubjectResultDAO;
import com.moeketsi.dao.SubjectStreamsDAO;
import java.util.ArrayList;
import javax.swing.JFrame;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Moeketsi Tsotetsi
 */
public class MarksFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MarksFrame.class.getName());
    private ArrayList<Subject> arSubjects = new ArrayList<>();
    private List<SubjectStreams> arStreams = new ArrayList<>();
    private int stream_id = 0;

    /**
     * Creates new form AddSubjectsFrame
     */
    public MarksFrame() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        loadStreams();
    }
    
    
    private void loadStreams(){
        cmbSubject.removeAllItems();
        try {
            arStreams = SubjectStreamsDAO.getAllSubjectStreams();
            
            for (int i = 0; i < arStreams.size(); i++) {
                cmbStream.addItem(arStreams.get(i).toString());
            }
        } catch (SQLException e) {
            System.out.println("Something went wrong : "+ e.getMessage());
            JOptionPane.showConfirmDialog(this, "Problem loading subject streams");
        }
    } 
    
    private void loadSubjectStreams(String streamName){
        if(streamName!=null || streamName.isEmpty()){
            
            for (int i = 0; i < arStreams.size(); i++) {
                if(arStreams.get(i).getStreamName().equalsIgnoreCase(streamName)){
                    stream_id = arStreams.get(i).getId();
                }
                
            }
        }else{
            JOptionPane.showMessageDialog(this, "Please select stream");
        }
        
        
        try {
          arSubjects = SubjectDAO.getSubjectsByStreams(stream_id);
          
            for (int i = 0; i < arSubjects.size(); i++) {
                cmbSubject.addItem(arSubjects.get(i).getSubjecName());
                
            }
            
        } catch (SQLException e) {
            
            System.out.println("error loading subjects :"+e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnAddMarks = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbSubject = new javax.swing.JComboBox<>();
        txtExamMark = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCassMark1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbStream = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtGrade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter  Marks", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        btnAddMarks.setText("Add Marks");
        btnAddMarks.addActionListener(this::btnAddMarksActionPerformed);

        jLabel1.setText("Student ID");

        jLabel2.setText("Select Subject");

        jLabel3.setText("Cass Mark");

        jLabel4.setText("Exam Mark");

        jLabel5.setText("Select Stream");

        cmbStream.addActionListener(this::cmbStreamActionPerformed);

        jLabel6.setText("Grade");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtStudentID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSubject, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCassMark1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbStream, 0, 174, Short.MAX_VALUE)
                            .addComponent(txtExamMark, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(txtGrade, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnAddMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbStream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtCassMark1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtExamMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnAddMarks)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(394, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbStreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStreamActionPerformed
        cmbSubject.removeAllItems();
        String stringStream = cmbStream.getSelectedItem().toString();
        loadSubjectStreams(stringStream);
        
    }//GEN-LAST:event_cmbStreamActionPerformed

    private void btnAddMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMarksActionPerformed
        int studentId = Integer.parseInt(txtStudentID.getText());
        Subject  subject = null;
        String result;
        Student st = null;
        int cassMark = Integer.parseInt(txtCassMark1.getText());
        int examMark = Integer.parseInt(txtExamMark.getText());
        
        String  strSubject = cmbSubject.getSelectedItem().toString();
        String grade = txtGrade.getText();
        if(!txtStudentID.getText().isBlank() || !txtCassMark1.getText().isBlank()
                || !txtExamMark.getText().isBlank() || !txtGrade.getText().isBlank()){
            
            for (int i = 0; i < arSubjects.size(); i++) {
                if(arSubjects.get(i).getSubjecName().equalsIgnoreCase(strSubject)){
                    subject = arSubjects.get(i);
                }
                
            }
            
            try {
                st = StudentDAO.findById(studentId);
  
                SubjectResult sr = new SubjectResult(subject, cassMark, examMark, st, grade);
                
                result = SubjectResultDAO.addSubjectResult(sr);
                
                JOptionPane.showMessageDialog(this, result);
                
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }catch(IllegalArgumentException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            
            
        }else{
            JOptionPane.showMessageDialog(this, "Please enter all student details");
        }
        
        
    }//GEN-LAST:event_btnAddMarksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MarksFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMarks;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbStream;
    private javax.swing.JComboBox<String> cmbSubject;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCassMark1;
    private javax.swing.JTextField txtExamMark;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtStudentID;
    // End of variables declaration//GEN-END:variables
}
