/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.moeketsi.gui;
import com.moeketsi.classes.Subject;
import com.moeketsi.dao.SubjectDAO;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.List;
import com.moeketsi.classes.SubjectStreams;
import com.moeketsi.dao.SubjectStreamsDAO;
import javax.swing.JFrame;
/**
 *
 * @author Moeketsi Tsotetsi
 */
public class Subjects extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Subjects.class.getName());
    private List<SubjectStreams> arSubjectStreams ;

    /**
     * Creates new form Subjects
     */
    public Subjects() {
        initComponents();
        loadSubjectStreams();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }
    
    
    public void loadSubjectStreams(){
        try {
            arSubjectStreams = SubjectStreamsDAO.getAllSubjectStreams();
            
            
            
            for (int i = 0; i < arSubjectStreams.size(); i++) {
                cmbSelectSream.addItem(arSubjectStreams.get(i).toString());
                
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Something went wrong while retrieving subkect streams", "Error",JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }

    
    private String addSubject(Subject sb){
    try {
        return SubjectDAO.addSbject(sb);  // Using the correctly named DAO method
    } catch (SQLException e) {
        // Log the error
        System.err.println("Database error: " + e.getMessage());
        e.printStackTrace();
        
        // Show user-friendly message
        JOptionPane.showMessageDialog(this, 
            "Database error occurred. Please try again.",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        return null;  // Return null on error
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        btnAddSubject = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSubjectName = new javax.swing.JTextField();
        AddSbject = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbSelectSream = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Subjects", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnAddSubject.setBorder(javax.swing.BorderFactory.createTitledBorder("Subject Details"));

        jLabel2.setText("Enter Subject Name");

        AddSbject.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        AddSbject.setText("Add Subject");
        AddSbject.addActionListener(this::AddSbjectActionPerformed);

        jLabel3.setText("Select Stream");

        javax.swing.GroupLayout btnAddSubjectLayout = new javax.swing.GroupLayout(btnAddSubject);
        btnAddSubject.setLayout(btnAddSubjectLayout);
        btnAddSubjectLayout.setHorizontalGroup(
            btnAddSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddSubjectLayout.createSequentialGroup()
                .addGroup(btnAddSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnAddSubjectLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(btnAddSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98)
                        .addGroup(btnAddSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSelectSream, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(btnAddSubjectLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(AddSbject)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        btnAddSubjectLayout.setVerticalGroup(
            btnAddSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddSubjectLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(btnAddSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(btnAddSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(cmbSelectSream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(AddSbject)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddSbjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSbjectActionPerformed
        
        
         try {
        String strStream =   cmbSelectSream.getSelectedItem().toString();
        
        SubjectStreams ss = null;
        
             for (int i = 0; i < arSubjectStreams.size(); i++) {
                 if(arSubjectStreams.get(i).getStreamName().equalsIgnoreCase(strStream)){
                     ss = arSubjectStreams.get(i);
                 }
                 
             }
        
        String subjectName = txtSubjectName.getText().trim();
        if (subjectName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Subject Name cannot be empty");
            return;
        }
        
        // Create subject object (may throw IllegalArgumentException from your class)
        Subject sb = new Subject(subjectName, ss);
        System.out.println("Class in gui: " + sb);
        
        // Add subject
        String result = addSubject(sb);
        
        // Handle result
        if (result != null) {
            JOptionPane.showMessageDialog(this, 
                "Success: " + result,
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
            // Clear fields on success
            txtSubjectName.setText("");
        } else {
            JOptionPane.showMessageDialog(this, 
                "Failed to add subject",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        
    } catch (IllegalArgumentException e) {
        // Catch validation errors from Subject class
        JOptionPane.showMessageDialog(this,
            "Invalid subject data: " + e.getMessage(),
            "Validation Error",
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_AddSbjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Subjects().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSbject;
    private javax.swing.JPanel btnAddSubject;
    private javax.swing.JComboBox<String> cmbSelectSream;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField txtSubjectName;
    // End of variables declaration//GEN-END:variables
}
