/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.moeketsi.gui;
import com.moeketsi.classes.Subject;
import com.moeketsi.dao.SubjectDAO;
import javax.swing.JOptionPane;
import java.sql.SQLException;
/**
 *
 * @author Moeketsi Tsotetsi
 */
public class Subjects extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Subjects.class.getName());

    /**
     * Creates new form Subjects
     */
    public Subjects() {
        initComponents();
    }

    
    private String addSubject(Subject sb){
    try {
        return SubjectDAO.addSbject(sb);  // Using the correctly named DAO method
    } catch (SQLException e) {
        // Log the error
        System.err.println("Database error: " + e.getMessage());
        e.printStackTrace();
        
        // Show user-friendly message
        JOptionPane.showMessageDialog(this, 
            "Database error occurred. Please try again.",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        return null;  // Return null on error
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        btnAddSubject = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSubjectCode = new javax.swing.JTextField();
        txtSubjectName = new javax.swing.JTextField();
        AddSbject = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Subjects", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnAddSubject.setBorder(javax.swing.BorderFactory.createTitledBorder("Subject Details"));

        jLabel1.setText("Enter Subject Code");

        jLabel2.setText("Enter Subject Name");

        AddSbject.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        AddSbject.setText("Add Subject");
        AddSbject.addActionListener(this::AddSbjectActionPerformed);

        javax.swing.GroupLayout btnAddSubjectLayout = new javax.swing.GroupLayout(btnAddSubject);
        btnAddSubject.setLayout(btnAddSubjectLayout);
        btnAddSubjectLayout.setHorizontalGroup(
            btnAddSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddSubjectLayout.createSequentialGroup()
                .addGroup(btnAddSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnAddSubjectLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(btnAddSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(85, 85, 85)
                        .addGroup(btnAddSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSubjectCode)
                            .addComponent(txtSubjectName, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
                    .addGroup(btnAddSubjectLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(AddSbject)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        btnAddSubjectLayout.setVerticalGroup(
            btnAddSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddSubjectLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(btnAddSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(btnAddSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(AddSbject)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddSbjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSbjectActionPerformed
        
        
         try {
        // Validate inputs
        String codeText = txtSubjectCode.getText().trim();
        if (codeText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Subject Code cannot be empty");
            return;
        }
        
        int subjectCode;
        try {
            subjectCode = Integer.parseInt(codeText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Subject Code must be a valid number");
            return;
        }
        
        String subjectName = txtSubjectName.getText().trim();
        if (subjectName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Subject Name cannot be empty");
            return;
        }
        
        // Create subject object (may throw IllegalArgumentException from your class)
        Subject sb = new Subject(subjectCode, subjectName);
        System.out.println("Class in gui: " + sb);
        
        // Add subject
        String result = addSubject(sb);
        
        // Handle result
        if (result != null) {
            JOptionPane.showMessageDialog(this, 
                "Success: " + result,
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
            // Clear fields on success
            txtSubjectCode.setText("");
            txtSubjectName.setText("");
        } else {
            JOptionPane.showMessageDialog(this, 
                "Failed to add subject",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        
    } catch (IllegalArgumentException e) {
        // Catch validation errors from Subject class
        JOptionPane.showMessageDialog(this,
            "Invalid subject data: " + e.getMessage(),
            "Validation Error",
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_AddSbjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Subjects().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSbject;
    private javax.swing.JPanel btnAddSubject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField txtSubjectCode;
    private javax.swing.JTextField txtSubjectName;
    // End of variables declaration//GEN-END:variables
}
